import { Question, Section, UIN } from '../types';

export const mockQuestions: Question[] = [
  // Mathematics - 20 questions
  {
    id: 'math-1',
    section: 'Mathematics',
    question: 'What is 15 + 27?',
    optionA: '40',
    optionB: '42',
    optionC: '44',
    optionD: '46',
    correctAnswer: 'B',
  },
  {
    id: 'math-2',
    section: 'Mathematics',
    question: 'What is 12 × 8?',
    optionA: '84',
    optionB: '92',
    optionC: '96',
    optionD: '100',
    correctAnswer: 'C',
  },
  {
    id: 'math-3',
    section: 'Mathematics',
    question: 'What is 144 ÷ 12?',
    optionA: '10',
    optionB: '11',
    optionC: '12',
    optionD: '13',
    correctAnswer: 'C',
  },
  {
    id: 'math-4',
    section: 'Mathematics',
    question: 'What is the square root of 81?',
    optionA: '7',
    optionB: '8',
    optionC: '9',
    optionD: '10',
    correctAnswer: 'C',
  },
  {
    id: 'math-5',
    section: 'Mathematics',
    question: 'What is 25% of 200?',
    optionA: '25',
    optionB: '40',
    optionC: '50',
    optionD: '75',
    correctAnswer: 'C',
  },
  {
    id: 'math-6',
    section: 'Mathematics',
    question: 'If x + 5 = 12, what is x?',
    optionA: '5',
    optionB: '6',
    optionC: '7',
    optionD: '8',
    correctAnswer: 'C',
  },
  {
    id: 'math-7',
    section: 'Mathematics',
    question: 'What is 3² + 4²?',
    optionA: '21',
    optionB: '23',
    optionC: '25',
    optionD: '27',
    correctAnswer: 'C',
  },
  {
    id: 'math-8',
    section: 'Mathematics',
    question: 'What is the perimeter of a square with side 8cm?',
    optionA: '24cm',
    optionB: '28cm',
    optionC: '32cm',
    optionD: '36cm',
    correctAnswer: 'C',
  },
  {
    id: 'math-9',
    section: 'Mathematics',
    question: 'What is 0.5 as a fraction?',
    optionA: '1/3',
    optionB: '1/2',
    optionC: '2/3',
    optionD: '3/4',
    correctAnswer: 'B',
  },
  {
    id: 'math-10',
    section: 'Mathematics',
    question: 'What is 7 × 9?',
    optionA: '54',
    optionB: '56',
    optionC: '63',
    optionD: '72',
    correctAnswer: 'C',
  },
  {
    id: 'math-11',
    section: 'Mathematics',
    question: 'What is the area of a rectangle 5cm × 8cm?',
    optionA: '30cm²',
    optionB: '35cm²',
    optionC: '40cm²',
    optionD: '45cm²',
    correctAnswer: 'C',
  },
  {
    id: 'math-12',
    section: 'Mathematics',
    question: 'What is 100 - 37?',
    optionA: '57',
    optionB: '63',
    optionC: '67',
    optionD: '73',
    correctAnswer: 'B',
  },
  {
    id: 'math-13',
    section: 'Mathematics',
    question: 'What is 2/5 as a decimal?',
    optionA: '0.2',
    optionB: '0.3',
    optionC: '0.4',
    optionD: '0.5',
    correctAnswer: 'C',
  },
  {
    id: 'math-14',
    section: 'Mathematics',
    question: 'What is the next prime number after 7?',
    optionA: '9',
    optionB: '10',
    optionC: '11',
    optionD: '13',
    correctAnswer: 'C',
  },
  {
    id: 'math-15',
    section: 'Mathematics',
    question: 'What is 15% of 80?',
    optionA: '10',
    optionB: '12',
    optionC: '14',
    optionD: '16',
    correctAnswer: 'B',
  },
  {
    id: 'math-16',
    section: 'Mathematics',
    question: 'What is the sum of angles in a triangle?',
    optionA: '90°',
    optionB: '120°',
    optionC: '180°',
    optionD: '360°',
    correctAnswer: 'C',
  },
  {
    id: 'math-17',
    section: 'Mathematics',
    question: 'What is 6³?',
    optionA: '180',
    optionB: '196',
    optionC: '216',
    optionD: '256',
    correctAnswer: 'C',
  },
  {
    id: 'math-18',
    section: 'Mathematics',
    question: 'What is the LCM of 4 and 6?',
    optionA: '8',
    optionB: '10',
    optionC: '12',
    optionD: '24',
    correctAnswer: 'C',
  },
  {
    id: 'math-19',
    section: 'Mathematics',
    question: 'What is 48 ÷ 6?',
    optionA: '6',
    optionB: '7',
    optionC: '8',
    optionD: '9',
    correctAnswer: 'C',
  },
  {
    id: 'math-20',
    section: 'Mathematics',
    question: 'What is the value of π (pi) approximately?',
    optionA: '2.14',
    optionB: '3.14',
    optionC: '4.14',
    optionD: '5.14',
    correctAnswer: 'B',
  },

  // English - 20 questions
  {
    id: 'eng-1',
    section: 'English',
    question: 'Which word is a noun?',
    optionA: 'Running',
    optionB: 'Quickly',
    optionC: 'Beautiful',
    optionD: 'Happiness',
    correctAnswer: 'D',
  },
  {
    id: 'eng-2',
    section: 'English',
    question: 'What is the past tense of "go"?',
    optionA: 'Goes',
    optionB: 'Gone',
    optionC: 'Went',
    optionD: 'Going',
    correctAnswer: 'C',
  },
  {
    id: 'eng-3',
    section: 'English',
    question: 'Which is the correct spelling?',
    optionA: 'Recieve',
    optionB: 'Receive',
    optionC: 'Receve',
    optionD: 'Receeve',
    correctAnswer: 'B',
  },
  {
    id: 'eng-4',
    section: 'English',
    question: 'What type of word is "quickly"?',
    optionA: 'Noun',
    optionB: 'Verb',
    optionC: 'Adjective',
    optionD: 'Adverb',
    correctAnswer: 'D',
  },
  {
    id: 'eng-5',
    section: 'English',
    question: 'Which sentence is grammatically correct?',
    optionA: 'She don\'t like apples',
    optionB: 'She doesn\'t likes apples',
    optionC: 'She doesn\'t like apples',
    optionD: 'She doesn\'t liking apples',
    correctAnswer: 'C',
  },
  {
    id: 'eng-6',
    section: 'English',
    question: 'What is a synonym for "happy"?',
    optionA: 'Sad',
    optionB: 'Angry',
    optionC: 'Joyful',
    optionD: 'Tired',
    correctAnswer: 'C',
  },
  {
    id: 'eng-7',
    section: 'English',
    question: 'Which is a collective noun?',
    optionA: 'Dog',
    optionB: 'Team',
    optionC: 'Book',
    optionD: 'Chair',
    correctAnswer: 'B',
  },
  {
    id: 'eng-8',
    section: 'English',
    question: 'What is the plural of "child"?',
    optionA: 'Childs',
    optionB: 'Childes',
    optionC: 'Children',
    optionD: 'Childrens',
    correctAnswer: 'C',
  },
  {
    id: 'eng-9',
    section: 'English',
    question: 'Which word is an adjective?',
    optionA: 'Run',
    optionB: 'Beautiful',
    optionC: 'Quickly',
    optionD: 'Happiness',
    correctAnswer: 'B',
  },
  {
    id: 'eng-10',
    section: 'English',
    question: 'What is an antonym for "hot"?',
    optionA: 'Warm',
    optionB: 'Cold',
    optionC: 'Burning',
    optionD: 'Heated',
    correctAnswer: 'B',
  },
  {
    id: 'eng-11',
    section: 'English',
    question: 'Which sentence uses correct punctuation?',
    optionA: 'Hello how are you',
    optionB: 'Hello, how are you?',
    optionC: 'Hello how are you.',
    optionD: 'Hello. how are you',
    correctAnswer: 'B',
  },
  {
    id: 'eng-12',
    section: 'English',
    question: 'What is the superlative form of "good"?',
    optionA: 'Gooder',
    optionB: 'Goodest',
    optionC: 'Better',
    optionD: 'Best',
    correctAnswer: 'D',
  },
  {
    id: 'eng-13',
    section: 'English',
    question: 'Which is a proper noun?',
    optionA: 'city',
    optionB: 'London',
    optionC: 'school',
    optionD: 'teacher',
    correctAnswer: 'B',
  },
  {
    id: 'eng-14',
    section: 'English',
    question: 'What is the comparative form of "big"?',
    optionA: 'Biger',
    optionB: 'Bigger',
    optionC: 'More big',
    optionD: 'Biggest',
    correctAnswer: 'B',
  },
  {
    id: 'eng-15',
    section: 'English',
    question: 'Which word is a verb?',
    optionA: 'Table',
    optionB: 'Beautiful',
    optionC: 'Jump',
    optionD: 'Quickly',
    correctAnswer: 'C',
  },
  {
    id: 'eng-16',
    section: 'English',
    question: 'What is the past participle of "write"?',
    optionA: 'Wrote',
    optionB: 'Writing',
    optionC: 'Written',
    optionD: 'Writes',
    correctAnswer: 'C',
  },
  {
    id: 'eng-17',
    section: 'English',
    question: 'Which is the correct contraction?',
    optionA: 'Wo\'nt',
    optionB: 'Won\'t',
    optionC: 'Wont\'',
    optionD: 'Wo\'not',
    correctAnswer: 'B',
  },
  {
    id: 'eng-18',
    section: 'English',
    question: 'What is a homophone for "write"?',
    optionA: 'Right',
    optionB: 'Wrote',
    optionC: 'Rite',
    optionD: 'Both A and C',
    correctAnswer: 'D',
  },
  {
    id: 'eng-19',
    section: 'English',
    question: 'Which is a preposition?',
    optionA: 'Under',
    optionB: 'Jump',
    optionC: 'Beautiful',
    optionD: 'Quickly',
    correctAnswer: 'A',
  },
  {
    id: 'eng-20',
    section: 'English',
    question: 'What is the plural of "tooth"?',
    optionA: 'Tooths',
    optionB: 'Toothes',
    optionC: 'Teeth',
    optionD: 'Teeths',
    correctAnswer: 'C',
  },

  // Science - 20 questions
  {
    id: 'sci-1',
    section: 'Science',
    question: 'What is the chemical symbol for water?',
    optionA: 'O2',
    optionB: 'H2O',
    optionC: 'CO2',
    optionD: 'H2',
    correctAnswer: 'B',
  },
  {
    id: 'sci-2',
    section: 'Science',
    question: 'How many planets are in our solar system?',
    optionA: '7',
    optionB: '8',
    optionC: '9',
    optionD: '10',
    correctAnswer: 'B',
  },
  {
    id: 'sci-3',
    section: 'Science',
    question: 'What is the hardest natural substance on Earth?',
    optionA: 'Gold',
    optionB: 'Iron',
    optionC: 'Diamond',
    optionD: 'Steel',
    correctAnswer: 'C',
  },
  {
    id: 'sci-4',
    section: 'Science',
    question: 'What gas do plants absorb from the atmosphere?',
    optionA: 'Oxygen',
    optionB: 'Nitrogen',
    optionC: 'Carbon Dioxide',
    optionD: 'Hydrogen',
    correctAnswer: 'C',
  },
  {
    id: 'sci-5',
    section: 'Science',
    question: 'What is the center of an atom called?',
    optionA: 'Electron',
    optionB: 'Proton',
    optionC: 'Neutron',
    optionD: 'Nucleus',
    correctAnswer: 'D',
  },
  {
    id: 'sci-6',
    section: 'Science',
    question: 'What is the boiling point of water?',
    optionA: '50°C',
    optionB: '75°C',
    optionC: '100°C',
    optionD: '125°C',
    correctAnswer: 'C',
  },
  {
    id: 'sci-7',
    section: 'Science',
    question: 'What organ pumps blood through the body?',
    optionA: 'Brain',
    optionB: 'Liver',
    optionC: 'Lungs',
    optionD: 'Heart',
    correctAnswer: 'D',
  },
  {
    id: 'sci-8',
    section: 'Science',
    question: 'What is the largest planet in our solar system?',
    optionA: 'Earth',
    optionB: 'Mars',
    optionC: 'Jupiter',
    optionD: 'Saturn',
    correctAnswer: 'C',
  },
  {
    id: 'sci-9',
    section: 'Science',
    question: 'What is the speed of light?',
    optionA: '300,000 km/s',
    optionB: '150,000 km/s',
    optionC: '450,000 km/s',
    optionD: '600,000 km/s',
    correctAnswer: 'A',
  },
  {
    id: 'sci-10',
    section: 'Science',
    question: 'What is photosynthesis?',
    optionA: 'Animal respiration',
    optionB: 'Plant food production',
    optionC: 'Water evaporation',
    optionD: 'Rock formation',
    correctAnswer: 'B',
  },
  {
    id: 'sci-11',
    section: 'Science',
    question: 'How many bones are in the adult human body?',
    optionA: '186',
    optionB: '206',
    optionC: '226',
    optionD: '246',
    correctAnswer: 'B',
  },
  {
    id: 'sci-12',
    section: 'Science',
    question: 'What is the chemical symbol for gold?',
    optionA: 'Go',
    optionB: 'Gd',
    optionC: 'Au',
    optionD: 'Ag',
    correctAnswer: 'C',
  },
  {
    id: 'sci-13',
    section: 'Science',
    question: 'What type of animal is a frog?',
    optionA: 'Mammal',
    optionB: 'Reptile',
    optionC: 'Amphibian',
    optionD: 'Fish',
    correctAnswer: 'C',
  },
  {
    id: 'sci-14',
    section: 'Science',
    question: 'What is the smallest unit of life?',
    optionA: 'Atom',
    optionB: 'Cell',
    optionC: 'Molecule',
    optionD: 'Organ',
    correctAnswer: 'B',
  },
  {
    id: 'sci-15',
    section: 'Science',
    question: 'What causes tides in the ocean?',
    optionA: 'Wind',
    optionB: 'The Moon',
    optionC: 'The Sun',
    optionD: 'Earthquakes',
    correctAnswer: 'B',
  },
  {
    id: 'sci-16',
    section: 'Science',
    question: 'What is the largest organ in the human body?',
    optionA: 'Heart',
    optionB: 'Brain',
    optionC: 'Liver',
    optionD: 'Skin',
    correctAnswer: 'D',
  },
  {
    id: 'sci-17',
    section: 'Science',
    question: 'What is DNA?',
    optionA: 'A type of protein',
    optionB: 'Genetic material',
    optionC: 'A vitamin',
    optionD: 'A mineral',
    correctAnswer: 'B',
  },
  {
    id: 'sci-18',
    section: 'Science',
    question: 'What is the process by which water changes to vapor?',
    optionA: 'Condensation',
    optionB: 'Precipitation',
    optionC: 'Evaporation',
    optionD: 'Sublimation',
    correctAnswer: 'C',
  },
  {
    id: 'sci-19',
    section: 'Science',
    question: 'What is the main gas in Earth\'s atmosphere?',
    optionA: 'Oxygen',
    optionB: 'Carbon Dioxide',
    optionC: 'Nitrogen',
    optionD: 'Hydrogen',
    correctAnswer: 'C',
  },
  {
    id: 'sci-20',
    section: 'Science',
    question: 'What force keeps us on the ground?',
    optionA: 'Magnetism',
    optionB: 'Friction',
    optionC: 'Gravity',
    optionD: 'Inertia',
    correctAnswer: 'C',
  },

  // Social Studies - 20 questions
  {
    id: 'ss-1',
    section: 'Social Studies',
    question: 'Who was the first President of the United States?',
    optionA: 'Abraham Lincoln',
    optionB: 'George Washington',
    optionC: 'Thomas Jefferson',
    optionD: 'John Adams',
    correctAnswer: 'B',
  },
  {
    id: 'ss-2',
    section: 'Social Studies',
    question: 'What is the capital of France?',
    optionA: 'London',
    optionB: 'Berlin',
    optionC: 'Paris',
    optionD: 'Madrid',
    correctAnswer: 'C',
  },
  {
    id: 'ss-3',
    section: 'Social Studies',
    question: 'In which year did World War II end?',
    optionA: '1943',
    optionB: '1944',
    optionC: '1945',
    optionD: '1946',
    correctAnswer: 'C',
  },
  {
    id: 'ss-4',
    section: 'Social Studies',
    question: 'Which continent is the Sahara Desert located in?',
    optionA: 'Asia',
    optionB: 'Africa',
    optionC: 'Australia',
    optionD: 'South America',
    correctAnswer: 'B',
  },
  {
    id: 'ss-5',
    section: 'Social Studies',
    question: 'What is the longest river in the world?',
    optionA: 'Amazon',
    optionB: 'Mississippi',
    optionC: 'Nile',
    optionD: 'Yangtze',
    correctAnswer: 'C',
  },
  {
    id: 'ss-6',
    section: 'Social Studies',
    question: 'Who wrote the Declaration of Independence?',
    optionA: 'Benjamin Franklin',
    optionB: 'George Washington',
    optionC: 'Thomas Jefferson',
    optionD: 'John Adams',
    correctAnswer: 'C',
  },
  {
    id: 'ss-7',
    section: 'Social Studies',
    question: 'How many continents are there?',
    optionA: '5',
    optionB: '6',
    optionC: '7',
    optionD: '8',
    correctAnswer: 'C',
  },
  {
    id: 'ss-8',
    section: 'Social Studies',
    question: 'What is the largest ocean on Earth?',
    optionA: 'Atlantic',
    optionB: 'Indian',
    optionC: 'Arctic',
    optionD: 'Pacific',
    correctAnswer: 'D',
  },
  {
    id: 'ss-9',
    section: 'Social Studies',
    question: 'In which city is the Statue of Liberty located?',
    optionA: 'Washington D.C.',
    optionB: 'New York',
    optionC: 'Boston',
    optionD: 'Philadelphia',
    correctAnswer: 'B',
  },
  {
    id: 'ss-10',
    section: 'Social Studies',
    question: 'What is the capital of Japan?',
    optionA: 'Beijing',
    optionB: 'Seoul',
    optionC: 'Tokyo',
    optionD: 'Bangkok',
    correctAnswer: 'C',
  },
  {
    id: 'ss-11',
    section: 'Social Studies',
    question: 'Who was known as the "Father of India"?',
    optionA: 'Jawaharlal Nehru',
    optionB: 'Mahatma Gandhi',
    optionC: 'Subhas Chandra Bose',
    optionD: 'Sardar Patel',
    correctAnswer: 'B',
  },
  {
    id: 'ss-12',
    section: 'Social Studies',
    question: 'Which ancient wonder is located in Egypt?',
    optionA: 'Colosseum',
    optionB: 'Taj Mahal',
    optionC: 'Great Wall',
    optionD: 'Pyramids of Giza',
    correctAnswer: 'D',
  },
  {
    id: 'ss-13',
    section: 'Social Studies',
    question: 'What is the smallest country in the world?',
    optionA: 'Monaco',
    optionB: 'Vatican City',
    optionC: 'San Marino',
    optionD: 'Liechtenstein',
    correctAnswer: 'B',
  },
  {
    id: 'ss-14',
    section: 'Social Studies',
    question: 'In which year did Christopher Columbus discover America?',
    optionA: '1492',
    optionB: '1500',
    optionC: '1520',
    optionD: '1607',
    correctAnswer: 'A',
  },
  {
    id: 'ss-15',
    section: 'Social Studies',
    question: 'What is the capital of Australia?',
    optionA: 'Sydney',
    optionB: 'Melbourne',
    optionC: 'Canberra',
    optionD: 'Brisbane',
    correctAnswer: 'C',
  },
  {
    id: 'ss-16',
    section: 'Social Studies',
    question: 'Which mountain is the tallest in the world?',
    optionA: 'K2',
    optionB: 'Mount Everest',
    optionC: 'Kilimanjaro',
    optionD: 'Mont Blanc',
    correctAnswer: 'B',
  },
  {
    id: 'ss-17',
    section: 'Social Studies',
    question: 'Who was the first man to walk on the moon?',
    optionA: 'Buzz Aldrin',
    optionB: 'Yuri Gagarin',
    optionC: 'Neil Armstrong',
    optionD: 'John Glenn',
    correctAnswer: 'C',
  },
  {
    id: 'ss-18',
    section: 'Social Studies',
    question: 'What is the currency of the United Kingdom?',
    optionA: 'Euro',
    optionB: 'Dollar',
    optionC: 'Pound Sterling',
    optionD: 'Franc',
    correctAnswer: 'C',
  },
  {
    id: 'ss-19',
    section: 'Social Studies',
    question: 'Which country is known as the "Land of the Rising Sun"?',
    optionA: 'China',
    optionB: 'Japan',
    optionC: 'Korea',
    optionD: 'Thailand',
    correctAnswer: 'B',
  },
  {
    id: 'ss-20',
    section: 'Social Studies',
    question: 'What is the national language of Brazil?',
    optionA: 'Spanish',
    optionB: 'Portuguese',
    optionC: 'English',
    optionD: 'French',
    correctAnswer: 'B',
  },

  // General Knowledge - 20 questions
  {
    id: 'gk-1',
    section: 'General Knowledge',
    question: 'How many days are in a leap year?',
    optionA: '365',
    optionB: '366',
    optionC: '367',
    optionD: '364',
    correctAnswer: 'B',
  },
  {
    id: 'gk-2',
    section: 'General Knowledge',
    question: 'What is the largest mammal in the world?',
    optionA: 'Elephant',
    optionB: 'Giraffe',
    optionC: 'Blue Whale',
    optionD: 'Polar Bear',
    correctAnswer: 'C',
  },
  {
    id: 'gk-3',
    section: 'General Knowledge',
    question: 'How many colors are in a rainbow?',
    optionA: '5',
    optionB: '6',
    optionC: '7',
    optionD: '8',
    correctAnswer: 'C',
  },
  {
    id: 'gk-4',
    section: 'General Knowledge',
    question: 'What is the fastest land animal?',
    optionA: 'Lion',
    optionB: 'Cheetah',
    optionC: 'Leopard',
    optionD: 'Tiger',
    correctAnswer: 'B',
  },
  {
    id: 'gk-5',
    section: 'General Knowledge',
    question: 'How many hours are in a day?',
    optionA: '12',
    optionB: '20',
    optionC: '24',
    optionD: '36',
    correctAnswer: 'C',
  },
  {
    id: 'gk-6',
    section: 'General Knowledge',
    question: 'What is the national sport of Canada?',
    optionA: 'Ice Hockey',
    optionB: 'Basketball',
    optionC: 'Lacrosse',
    optionD: 'Both A and C',
    correctAnswer: 'D',
  },
  {
    id: 'gk-7',
    section: 'General Knowledge',
    question: 'How many sides does a hexagon have?',
    optionA: '4',
    optionB: '5',
    optionC: '6',
    optionD: '7',
    correctAnswer: 'C',
  },
  {
    id: 'gk-8',
    section: 'General Knowledge',
    question: 'What is the largest bird in the world?',
    optionA: 'Eagle',
    optionB: 'Ostrich',
    optionC: 'Penguin',
    optionD: 'Albatross',
    correctAnswer: 'B',
  },
  {
    id: 'gk-9',
    section: 'General Knowledge',
    question: 'How many strings does a standard guitar have?',
    optionA: '4',
    optionB: '5',
    optionC: '6',
    optionD: '7',
    correctAnswer: 'C',
  },
  {
    id: 'gk-10',
    section: 'General Knowledge',
    question: 'What is the primary ingredient in bread?',
    optionA: 'Rice',
    optionB: 'Flour',
    optionC: 'Sugar',
    optionD: 'Salt',
    correctAnswer: 'B',
  },
  {
    id: 'gk-11',
    section: 'General Knowledge',
    question: 'How many teeth does an adult human have?',
    optionA: '28',
    optionB: '30',
    optionC: '32',
    optionD: '34',
    correctAnswer: 'C',
  },
  {
    id: 'gk-12',
    section: 'General Knowledge',
    question: 'What is the world\'s most spoken language?',
    optionA: 'English',
    optionB: 'Spanish',
    optionC: 'Mandarin Chinese',
    optionD: 'Hindi',
    correctAnswer: 'C',
  },
  {
    id: 'gk-13',
    section: 'General Knowledge',
    question: 'How many Olympic rings are there?',
    optionA: '3',
    optionB: '4',
    optionC: '5',
    optionD: '6',
    correctAnswer: 'C',
  },
  {
    id: 'gk-14',
    section: 'General Knowledge',
    question: 'What is the tallest building in the world (as of 2024)?',
    optionA: 'Empire State Building',
    optionB: 'Burj Khalifa',
    optionC: 'Shanghai Tower',
    optionD: 'CN Tower',
    correctAnswer: 'B',
  },
  {
    id: 'gk-15',
    section: 'General Knowledge',
    question: 'How many minutes are in an hour?',
    optionA: '50',
    optionB: '60',
    optionC: '70',
    optionD: '100',
    correctAnswer: 'B',
  },
  {
    id: 'gk-16',
    section: 'General Knowledge',
    question: 'What is the symbol for recycling?',
    optionA: 'A tree',
    optionB: 'A circle',
    optionC: 'Three arrows in a triangle',
    optionD: 'A leaf',
    correctAnswer: 'C',
  },
  {
    id: 'gk-17',
    section: 'General Knowledge',
    question: 'How many weeks are in a year?',
    optionA: '48',
    optionB: '50',
    optionC: '52',
    optionD: '54',
    correctAnswer: 'C',
  },
  {
    id: 'gk-18',
    section: 'General Knowledge',
    question: 'What is the freezing point of water in Celsius?',
    optionA: '-10°C',
    optionB: '0°C',
    optionC: '10°C',
    optionD: '32°C',
    correctAnswer: 'B',
  },
  {
    id: 'gk-19',
    section: 'General Knowledge',
    question: 'How many players are on a soccer team?',
    optionA: '9',
    optionB: '10',
    optionC: '11',
    optionD: '12',
    correctAnswer: 'C',
  },
  {
    id: 'gk-20',
    section: 'General Knowledge',
    question: 'What is the primary color that is NOT red or blue?',
    optionA: 'Green',
    optionB: 'Yellow',
    optionC: 'Orange',
    optionD: 'Purple',
    correctAnswer: 'B',
  },
];

export const mockUINs: UIN[] = [
  {
    id: '1',
    code: 'TRN-ABC123',
    used: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    code: 'TRN-XYZ789',
    used: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    code: 'TRN-DEF456',
    used: true,
    usedBy: 'John Doe',
    usedAt: new Date(Date.now() - 86400000).toISOString(),
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const initializeMockData = () => {
  const existingData = localStorage.getItem('westend_diamond_academy_cbt');
  if (!existingData) {
    const initialData = {
      questions: mockQuestions,
      uins: mockUINs,
      results: [],
      currentSession: null,
    };
    localStorage.setItem('westend_diamond_academy_cbt', JSON.stringify(initialData));
  }
};
